name: Release on tag

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (historial completo + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Resolve commit tag
        id: tag
        shell: bash
        run: |
          set -euo pipefail
          ref="${GITHUB_REF_NAME:-}"
          if [[ -z "$ref" ]]; then
            echo "GITHUB_REF_NAME vacío (event: $GITHUB_EVENT_NAME)" >&2
            exit 1
          fi
          git fetch --tags --force --quiet
          sha="$(git rev-list -n 1 "$ref")"
          if [[ -z "$sha" ]]; then
            echo "Couldn't resolve the commit for the tag '$ref'." >&2
            git tag -l | sed 's/^/tag local: /' || true
            exit 1
          fi
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Verify that the tag is on master
        id: gate
        run: |
          git fetch origin master --quiet
          if git merge-base --is-ancestor "${{ steps.tag.outputs.sha }}" "origin/master"; then
            echo "on_master=true" >> "$GITHUB_OUTPUT"
          else
            echo "on_master=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Release
        if: steps.gate.outputs.on_master == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
